GET  http://localhost:3000/tasks

// GET http://localhost:3000/tasks/1

//PUT http://localhost:3000/tasks/6
//content-type: application/json

// {
//  "name": "Buy Milk",
//  "status": "completed"
// }

// DELETE http://localhost:3000/tasks/5


//POST http://localhost:3000/tasks
#content-type: application/json

#{
 #   "name": "Cozinhar couve",
 #   "status":"in progress"
#}
